---
- include_tasks: mopidy_debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: mopidy_rh.yml
  when: ansible_os_family == "RedHat"

- name: Install Mopidy packages
  package:
    name:
      - mopidy
      - gstreamer1.0-plugins-bad
    state: latest

- name: Install mopidy extensions.
  package:
    name: "{{ mopidy_extensions }}"
    state: latest
  notify: restart mopidy

- name: Ensure pip is available.
  package:
    name:
      - python3-pip
      - python3-setuptools
    state: latest
  when: mopidy_external_extensions

- name: Install Mopidy Python3 packages
  pip:
    executable: pip3
    name: "{{ mopidy_external_extensions }}"
    state: latest
  notify: restart mopidy
  when: mopidy_external_extensions

- name: Check if Iris is installed
  stat:
    path: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh
  register: stat_result

- name: Ensure Iris has access to install itself
  lineinfile:
    path: /etc/sudoers
    regexp: '^mopidy'
    line: "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh"
    validate: /usr/sbin/visudo -cf %s
  when: stat_result.stat.exists

- name: Configure Mopidy
  ini_file:
    dest: /etc/mopidy/mopidy.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mopidy_settings }}"
  notify: restart mopidy

- name: Ensure Mopidy is started on boot.
  service:
    name: mopidy
    state: started
    enabled: yes