- name: Enable the RPM Fusion repository
  yum:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: latest

- name: 'Update yum package cache'
  yum:
    update_cache: yes
    state: latest