---
- name: Add Mopidy PPA key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Install Mopidy Debian Buster Repo
  get_url:
    url: https://apt.mopidy.com/buster.list
    dest: /etc/apt/sources.list.d/mopidy.list
    force: no
    mode: 0644
    owner: root
    group: root

- name: 'Update APT package cache'
  apt:
    update_cache: yes